---
name: Build package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        env:
          SHELLCHECK_OPTS: -e SC1091

      - name: Build Debian package
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --no-sign --check-command=lintian
          extra-build-deps: lintian

      - name: Archive Debian artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: debian/artifacts
